
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file Diem.cs instead.
*/

#region using directives

using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

#endregion

namespace QuanLyHocSinhPTNK.Entities
{
	///<summary>
	/// An object representation of the 'Diem' table. [No description found the database]	
	///</summary>
	[Serializable, DataObject]
	[CLSCompliant(true)]
	public abstract partial class DiemBase : EntityBase, QuanLyHocSinhPTNK.Entities.IDiem, IEntityId<DiemKey>, System.IComparable, System.ICloneable, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private DiemEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private DiemEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private DiemEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Diem> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>	
		[field:NonSerialized]
		public event DiemEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event DiemEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="DiemBase"/> instance.
		///</summary>
		public DiemBase()
		{
			this.entityData = new DiemEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="DiemBase"/> instance.
		///</summary>
		///<param name="maDiem"></param>
		///<param name="diem15Phut"></param>
		///<param name="diem1Tiet"></param>
		///<param name="diemCuoiKy"></param>
		///<param name="dtb"></param>
		///<param name="maMon"></param>
		///<param name="maBangDiem"></param>
		///<param name="maHocKy"></param>
		public DiemBase(System.String maDiem, System.Double diem15Phut, System.Double diem1Tiet, 
			System.Double diemCuoiKy, System.Double dtb, System.String maMon, System.String maBangDiem, System.String maHocKy)
		{
			this.entityData = new DiemEntityData();
			this.backupData = null;

			this.MaDiem = maDiem;
			this.Diem15Phut = diem15Phut;
			this.Diem1Tiet = diem1Tiet;
			this.DiemCuoiKy = diemCuoiKy;
			this.Dtb = dtb;
			this.MaMon = maMon;
			this.MaBangDiem = maBangDiem;
			this.MaHocKy = maHocKy;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Diem"/> instance.
		///</summary>
		///<param name="maDiem"></param>
		///<param name="diem15Phut"></param>
		///<param name="diem1Tiet"></param>
		///<param name="diemCuoiKy"></param>
		///<param name="dtb"></param>
		///<param name="maMon"></param>
		///<param name="maBangDiem"></param>
		///<param name="maHocKy"></param>
		public static Diem CreateDiem(System.String maDiem, System.Double diem15Phut, System.Double diem1Tiet, 
			System.Double diemCuoiKy, System.Double dtb, System.String maMon, System.String maBangDiem, System.String maHocKy)
		{
			Diem newDiem = new Diem();
			newDiem.MaDiem = maDiem;
			newDiem.Diem15Phut = diem15Phut;
			newDiem.Diem1Tiet = diem1Tiet;
			newDiem.DiemCuoiKy = diemCuoiKy;
			newDiem.Dtb = dtb;
			newDiem.MaMon = maMon;
			newDiem.MaBangDiem = maBangDiem;
			newDiem.MaHocKy = maHocKy;
			return newDiem;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the MaDiem property. 
		///		
		/// </summary>
		/// <value>This type is nchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false, 10)]
		public virtual System.String MaDiem
		{
			get
			{
				return this.entityData.MaDiem; 
			}
			
			set
			{
				if (this.entityData.MaDiem == value)
					return;
					
				OnColumnChanging(DiemColumn.MaDiem, this.entityData.MaDiem);
				this.entityData.MaDiem = value;
				this.EntityId.MaDiem = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DiemColumn.MaDiem, this.entityData.MaDiem);
				OnPropertyChanged("MaDiem");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the MaDiem property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the MaDiem property.</remarks>
		/// <value>This type is nchar</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.String OriginalMaDiem
		{
			get { return this.entityData.OriginalMaDiem; }
			set { this.entityData.OriginalMaDiem = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the Diem15Phut property. 
		///		
		/// </summary>
		/// <value>This type is float.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Double Diem15Phut
		{
			get
			{
				return this.entityData.Diem15Phut; 
			}
			
			set
			{
				if (this.entityData.Diem15Phut == value)
					return;
					
				OnColumnChanging(DiemColumn.Diem15Phut, this.entityData.Diem15Phut);
				this.entityData.Diem15Phut = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DiemColumn.Diem15Phut, this.entityData.Diem15Phut);
				OnPropertyChanged("Diem15Phut");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Diem1Tiet property. 
		///		
		/// </summary>
		/// <value>This type is float.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Double Diem1Tiet
		{
			get
			{
				return this.entityData.Diem1Tiet; 
			}
			
			set
			{
				if (this.entityData.Diem1Tiet == value)
					return;
					
				OnColumnChanging(DiemColumn.Diem1Tiet, this.entityData.Diem1Tiet);
				this.entityData.Diem1Tiet = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DiemColumn.Diem1Tiet, this.entityData.Diem1Tiet);
				OnPropertyChanged("Diem1Tiet");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the DiemCuoiKy property. 
		///		
		/// </summary>
		/// <value>This type is float.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Double DiemCuoiKy
		{
			get
			{
				return this.entityData.DiemCuoiKy; 
			}
			
			set
			{
				if (this.entityData.DiemCuoiKy == value)
					return;
					
				OnColumnChanging(DiemColumn.DiemCuoiKy, this.entityData.DiemCuoiKy);
				this.entityData.DiemCuoiKy = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DiemColumn.DiemCuoiKy, this.entityData.DiemCuoiKy);
				OnPropertyChanged("DiemCuoiKy");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Dtb property. 
		///		
		/// </summary>
		/// <value>This type is float.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Double Dtb
		{
			get
			{
				return this.entityData.Dtb; 
			}
			
			set
			{
				if (this.entityData.Dtb == value)
					return;
					
				OnColumnChanging(DiemColumn.Dtb, this.entityData.Dtb);
				this.entityData.Dtb = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DiemColumn.Dtb, this.entityData.Dtb);
				OnPropertyChanged("Dtb");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MaMon property. 
		///		
		/// </summary>
		/// <value>This type is nchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 10)]
		public virtual System.String MaMon
		{
			get
			{
				return this.entityData.MaMon; 
			}
			
			set
			{
				if (this.entityData.MaMon == value)
					return;
					
				OnColumnChanging(DiemColumn.MaMon, this.entityData.MaMon);
				this.entityData.MaMon = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DiemColumn.MaMon, this.entityData.MaMon);
				OnPropertyChanged("MaMon");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MaBangDiem property. 
		///		
		/// </summary>
		/// <value>This type is nchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 10)]
		public virtual System.String MaBangDiem
		{
			get
			{
				return this.entityData.MaBangDiem; 
			}
			
			set
			{
				if (this.entityData.MaBangDiem == value)
					return;
					
				OnColumnChanging(DiemColumn.MaBangDiem, this.entityData.MaBangDiem);
				this.entityData.MaBangDiem = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DiemColumn.MaBangDiem, this.entityData.MaBangDiem);
				OnPropertyChanged("MaBangDiem");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MaHocKy property. 
		///		
		/// </summary>
		/// <value>This type is nchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 10)]
		public virtual System.String MaHocKy
		{
			get
			{
				return this.entityData.MaHocKy; 
			}
			
			set
			{
				if (this.entityData.MaHocKy == value)
					return;
					
				OnColumnChanging(DiemColumn.MaHocKy, this.entityData.MaHocKy);
				this.entityData.MaHocKy = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DiemColumn.MaHocKy, this.entityData.MaHocKy);
				OnPropertyChanged("MaHocKy");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="MonHoc"/>.
		/// </summary>
		/// <value>The source MonHoc for MaMon.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual MonHoc MaMonSource
      	{
            get { return entityData.MaMonSource; }
            set { entityData.MaMonSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="HocKy"/>.
		/// </summary>
		/// <value>The source HocKy for MaHocKy.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual HocKy MaHocKySource
      	{
            get { return entityData.MaHocKySource; }
            set { entityData.MaHocKySource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="BangDiem"/>.
		/// </summary>
		/// <value>The source BangDiem for MaBangDiem.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual BangDiem MaBangDiemSource
      	{
            get { return entityData.MaBangDiemSource; }
            set { entityData.MaBangDiemSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule(
				Validation.CommonRules.NotNull,
				new Validation.ValidationRuleArgs("MaDiem", "Ma Diem"));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("MaDiem", "Ma Diem", 10));
			ValidationRules.AddRule(
				Validation.CommonRules.NotNull,
				new Validation.ValidationRuleArgs("MaMon", "Ma Mon"));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("MaMon", "Ma Mon", 10));
			ValidationRules.AddRule(
				Validation.CommonRules.NotNull,
				new Validation.ValidationRuleArgs("MaBangDiem", "Ma Bang Diem"));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("MaBangDiem", "Ma Bang Diem", 10));
			ValidationRules.AddRule(
				Validation.CommonRules.NotNull,
				new Validation.ValidationRuleArgs("MaHocKy", "Ma Hoc Ky"));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("MaHocKy", "Ma Hoc Ky", 10));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "Diem"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"MaDiem", "Diem15Phut", "Diem1Tiet", "DiemCuoiKy", "DTB", "MaMon", "MaBangDiem", "MaHocKy"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as DiemEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Diem) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Diem>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Diem);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Diem Entity 
		///</summary>
		public virtual Diem Copy()
		{
			//shallow copy entity
			Diem copy = new Diem();
			copy.SuppressEntityEvents = true;
			copy.MaDiem = this.MaDiem;
			copy.OriginalMaDiem = this.OriginalMaDiem;
			copy.Diem15Phut = this.Diem15Phut;
			copy.Diem1Tiet = this.Diem1Tiet;
			copy.DiemCuoiKy = this.DiemCuoiKy;
			copy.Dtb = this.Dtb;
			copy.MaMon = this.MaMon;
			copy.MaBangDiem = this.MaBangDiem;
			copy.MaHocKy = this.MaHocKy;
			
			copy.MaMonSource = MakeCopyOf(this.MaMonSource) as MonHoc;
			copy.MaHocKySource = MakeCopyOf(this.MaHocKySource) as HocKy;
			copy.MaBangDiemSource = MakeCopyOf(this.MaBangDiemSource) as BangDiem;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		///  Returns a Typed Diem Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Diem DeepCopy()
		{
			return EntityHelper.Clone<Diem>(this as Diem);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as DiemEntityData;
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as DiemEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(DiemColumn column)
		{
			switch(column)
			{
					case DiemColumn.MaDiem:
					return entityData.MaDiem != _originalData.MaDiem;
					case DiemColumn.Diem15Phut:
					return entityData.Diem15Phut != _originalData.Diem15Phut;
					case DiemColumn.Diem1Tiet:
					return entityData.Diem1Tiet != _originalData.Diem1Tiet;
					case DiemColumn.DiemCuoiKy:
					return entityData.DiemCuoiKy != _originalData.DiemCuoiKy;
					case DiemColumn.Dtb:
					return entityData.Dtb != _originalData.Dtb;
					case DiemColumn.MaMon:
					return entityData.MaMon != _originalData.MaMon;
					case DiemColumn.MaBangDiem:
					return entityData.MaBangDiem != _originalData.MaBangDiem;
					case DiemColumn.MaHocKy:
					return entityData.MaHocKy != _originalData.MaHocKy;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if [has data changed]; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.MaDiem != _originalData.MaDiem;
			result = result || entityData.Diem15Phut != _originalData.Diem15Phut;
			result = result || entityData.Diem1Tiet != _originalData.Diem1Tiet;
			result = result || entityData.DiemCuoiKy != _originalData.DiemCuoiKy;
			result = result || entityData.Dtb != _originalData.Dtb;
			result = result || entityData.MaMon != _originalData.MaMon;
			result = result || entityData.MaBangDiem != _originalData.MaBangDiem;
			result = result || entityData.MaHocKy != _originalData.MaHocKy;
			return result;
}	
		
		#endregion

        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="DiemBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			if (Object1 is DiemBase)
				return Equals(this, (DiemBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="DiemBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.MaDiem.GetHashCode() ^ 
					this.Diem15Phut.GetHashCode() ^ 
					this.Diem1Tiet.GetHashCode() ^ 
					this.DiemCuoiKy.GetHashCode() ^ 
					this.Dtb.GetHashCode() ^ 
					this.MaMon.GetHashCode() ^ 
					this.MaBangDiem.GetHashCode() ^ 
					this.MaHocKy.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="DiemBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(DiemBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="DiemBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="DiemBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="DiemBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(DiemBase Object1, DiemBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.MaDiem != Object2.MaDiem)
				equal = false;
			if (Object1.Diem15Phut != Object2.Diem15Phut)
				equal = false;
			if (Object1.Diem1Tiet != Object2.Diem1Tiet)
				equal = false;
			if (Object1.DiemCuoiKy != Object2.DiemCuoiKy)
				equal = false;
			if (Object1.Dtb != Object2.Dtb)
				equal = false;
			if (Object1.MaMon != Object2.MaMon)
				equal = false;
			if (Object1.MaBangDiem != Object2.MaBangDiem)
				equal = false;
			if (Object1.MaHocKy != Object2.MaHocKy)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((DiemBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static DiemComparer GetComparer()
        {
            return new DiemComparer();
        }
        */

        // Comparer delegates back to Diem
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Diem rhs, DiemColumn which)
        {
            switch (which)
            {
            	
            	
            	case DiemColumn.MaDiem:
            		return this.MaDiem.CompareTo(rhs.MaDiem);
            		
            		                 
            	
            	
            	case DiemColumn.Diem15Phut:
            		return this.Diem15Phut.CompareTo(rhs.Diem15Phut);
            		
            		                 
            	
            	
            	case DiemColumn.Diem1Tiet:
            		return this.Diem1Tiet.CompareTo(rhs.Diem1Tiet);
            		
            		                 
            	
            	
            	case DiemColumn.DiemCuoiKy:
            		return this.DiemCuoiKy.CompareTo(rhs.DiemCuoiKy);
            		
            		                 
            	
            	
            	case DiemColumn.Dtb:
            		return this.Dtb.CompareTo(rhs.Dtb);
            		
            		                 
            	
            	
            	case DiemColumn.MaMon:
            		return this.MaMon.CompareTo(rhs.MaMon);
            		
            		                 
            	
            	
            	case DiemColumn.MaBangDiem:
            		return this.MaBangDiem.CompareTo(rhs.MaBangDiem);
            		
            		                 
            	
            	
            	case DiemColumn.MaHocKy:
            		return this.MaHocKy.CompareTo(rhs.MaHocKy);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<DiemKey> Members
		
		// member variable for the EntityId property
		private DiemKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual DiemKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new DiemKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Diem")
					.Append("|").Append( this.MaDiem.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{9}{8}- MaDiem: {0}{8}- Diem15Phut: {1}{8}- Diem1Tiet: {2}{8}- DiemCuoiKy: {3}{8}- Dtb: {4}{8}- MaMon: {5}{8}- MaBangDiem: {6}{8}- MaHocKy: {7}{8}", 
				this.MaDiem,
				this.Diem15Phut,
				this.Diem1Tiet,
				this.DiemCuoiKy,
				this.Dtb,
				this.MaMon,
				this.MaBangDiem,
				this.MaHocKy,
				System.Environment.NewLine, 
				this.GetType());
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'Diem' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class DiemEntityData : ICloneable
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
			/// <summary>			
			/// MaDiem : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "Diem"</remarks>
			public System.String MaDiem;
				
			/// <summary>
			/// keep a copy of the original so it can be used for editable primary keys.
			/// </summary>
			public System.String OriginalMaDiem;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// Diem15Phut : 
		/// </summary>
		public System.Double		  Diem15Phut = 0.0f;
		
		/// <summary>
		/// Diem1Tiet : 
		/// </summary>
		public System.Double		  Diem1Tiet = 0.0f;
		
		/// <summary>
		/// DiemCuoiKy : 
		/// </summary>
		public System.Double		  DiemCuoiKy = 0.0f;
		
		/// <summary>
		/// DTB : 
		/// </summary>
		public System.Double		  Dtb = 0.0f;
		
		/// <summary>
		/// MaMon : 
		/// </summary>
		public System.String		  MaMon = string.Empty;
		
		/// <summary>
		/// MaBangDiem : 
		/// </summary>
		public System.String		  MaBangDiem = string.Empty;
		
		/// <summary>
		/// MaHocKy : 
		/// </summary>
		public System.String		  MaHocKy = string.Empty;
		#endregion
			
		#region Source Foreign Key Property
				
		private MonHoc _maMonSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="MonHoc"/>.
		/// </summary>
		/// <value>The source MonHoc for MaMon.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual MonHoc MaMonSource
      	{
            get { return this._maMonSource; }
            set { this._maMonSource = value; }
      	}
		private HocKy _maHocKySource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="HocKy"/>.
		/// </summary>
		/// <value>The source HocKy for MaHocKy.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual HocKy MaHocKySource
      	{
            get { return this._maHocKySource; }
            set { this._maHocKySource = value; }
      	}
		private BangDiem _maBangDiemSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="BangDiem"/>.
		/// </summary>
		/// <value>The source BangDiem for MaBangDiem.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual BangDiem MaBangDiemSource
      	{
            get { return this._maBangDiemSource; }
            set { this._maBangDiemSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			DiemEntityData _tmp = new DiemEntityData();
						
			_tmp.MaDiem = this.MaDiem;
			_tmp.OriginalMaDiem = this.OriginalMaDiem;
			
			_tmp.Diem15Phut = this.Diem15Phut;
			_tmp.Diem1Tiet = this.Diem1Tiet;
			_tmp.DiemCuoiKy = this.DiemCuoiKy;
			_tmp.Dtb = this.Dtb;
			_tmp.MaMon = this.MaMon;
			_tmp.MaBangDiem = this.MaBangDiem;
			_tmp.MaHocKy = this.MaHocKy;
			
			#region Source Parent Composite Entities
			if (this.MaMonSource != null)
				_tmp.MaMonSource = MakeCopyOf(this.MaMonSource) as MonHoc;
			if (this.MaHocKySource != null)
				_tmp.MaHocKySource = MakeCopyOf(this.MaHocKySource) as HocKy;
			if (this.MaBangDiemSource != null)
				_tmp.MaBangDiemSource = MakeCopyOf(this.MaBangDiemSource) as BangDiem;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct



		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DiemColumn"/> which has raised the event.</param>
		public void OnColumnChanging(DiemColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DiemColumn"/> which has raised the event.</param>
		public void OnColumnChanged(DiemColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DiemColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanging(DiemColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				DiemEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new DiemEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DiemColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanged(DiemColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				DiemEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new DiemEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region DiemEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Diem"/> object.
	/// </remarks>
	public class DiemEventArgs : System.EventArgs
	{
		private DiemColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the DiemEventArgs class.
		///</summary>
		public DiemEventArgs(DiemColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the DiemEventArgs class.
		///</summary>
		public DiemEventArgs(DiemColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The DiemColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="DiemColumn" />
		public DiemColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Diem related events.
	///</summary>
	public delegate void DiemEventHandler(object sender, DiemEventArgs e);
	
	#region DiemComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class DiemComparer : System.Collections.Generic.IComparer<Diem>
	{
		DiemColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:DiemComparer"/> class.
        /// </summary>
		public DiemComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:DiemComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public DiemComparer(DiemColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="Diem"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="Diem"/> to compare.</param>
        /// <param name="b">The second <c>Diem</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Diem a, Diem b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Diem entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Diem a, Diem b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public DiemColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region DiemKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Diem"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class DiemKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the DiemKey class.
		/// </summary>
		public DiemKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the DiemKey class.
		/// </summary>
		public DiemKey(DiemBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.MaDiem = entity.MaDiem;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the DiemKey class.
		/// </summary>
		public DiemKey(System.String maDiem)
		{
			#region Init Properties

			this.MaDiem = maDiem;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private DiemBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public DiemBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the MaDiem property
		private System.String _maDiem;
		
		/// <summary>
		/// Gets or sets the MaDiem property.
		/// </summary>
		public System.String MaDiem
		{
			get { return _maDiem; }
			set
			{
				if ( this.Entity != null )
					this.Entity.MaDiem = value;
				
				_maDiem = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				MaDiem = ( values["MaDiem"] != null ) ? (System.String) EntityUtil.ChangeType(values["MaDiem"], typeof(System.String)) : string.Empty;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("MaDiem", MaDiem);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("MaDiem: {0}{1}",
								MaDiem,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region DiemColumn Enum
	
	/// <summary>
	/// Enumerate the Diem columns.
	/// </summary>
	[Serializable]
	public enum DiemColumn : int
	{
		/// <summary>
		/// MaDiem : 
		/// </summary>
		[EnumTextValue("MaDiem")]
		[ColumnEnum("MaDiem", typeof(System.String), System.Data.DbType.StringFixedLength, true, false, false, 10)]
		MaDiem = 1,
		/// <summary>
		/// Diem15Phut : 
		/// </summary>
		[EnumTextValue("Diem15Phut")]
		[ColumnEnum("Diem15Phut", typeof(System.Double), System.Data.DbType.Double, false, false, false)]
		Diem15Phut = 2,
		/// <summary>
		/// Diem1Tiet : 
		/// </summary>
		[EnumTextValue("Diem1Tiet")]
		[ColumnEnum("Diem1Tiet", typeof(System.Double), System.Data.DbType.Double, false, false, false)]
		Diem1Tiet = 3,
		/// <summary>
		/// DiemCuoiKy : 
		/// </summary>
		[EnumTextValue("DiemCuoiKy")]
		[ColumnEnum("DiemCuoiKy", typeof(System.Double), System.Data.DbType.Double, false, false, false)]
		DiemCuoiKy = 4,
		/// <summary>
		/// Dtb : 
		/// </summary>
		[EnumTextValue("DTB")]
		[ColumnEnum("DTB", typeof(System.Double), System.Data.DbType.Double, false, false, false)]
		Dtb = 5,
		/// <summary>
		/// MaMon : 
		/// </summary>
		[EnumTextValue("MaMon")]
		[ColumnEnum("MaMon", typeof(System.String), System.Data.DbType.StringFixedLength, false, false, false, 10)]
		MaMon = 6,
		/// <summary>
		/// MaBangDiem : 
		/// </summary>
		[EnumTextValue("MaBangDiem")]
		[ColumnEnum("MaBangDiem", typeof(System.String), System.Data.DbType.StringFixedLength, false, false, false, 10)]
		MaBangDiem = 7,
		/// <summary>
		/// MaHocKy : 
		/// </summary>
		[EnumTextValue("MaHocKy")]
		[ColumnEnum("MaHocKy", typeof(System.String), System.Data.DbType.StringFixedLength, false, false, false, 10)]
		MaHocKy = 8
	}//End enum

	#endregion DiemColumn Enum

} // end namespace
