

/*
	File Generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file HocSinhTest.cs instead.
*/

#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using QuanLyHocSinhPTNK.Entities;
using QuanLyHocSinhPTNK.Data;
using QuanLyHocSinhPTNK.Data.Bases;

#endregion

namespace QuanLyHocSinhPTNK.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="HocSinh"/> objects (entity, collection and repository).
    /// </summary>
   public partial class HocSinhTest
    {
    	// the HocSinh instance used to test the repository.
		private HocSinh mock;
		
		// the TList<HocSinh> instance used to test the repository.
		private TList<HocSinh> mockCollection;
		
		private static TransactionManager CreateTransaction()
		{
			TransactionManager transactionManager = null;
			if (DataRepository.Provider.IsTransactionSupported)
			{
				transactionManager = DataRepository.Provider.CreateTransaction();
				transactionManager.BeginTransaction(System.Data.IsolationLevel.ReadUncommitted);
			}			
			return transactionManager;
		}
		       
        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>        
        static public void Init_Generated()
        {		
        	System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the HocSinh Entity with the {0} --", QuanLyHocSinhPTNK.Data.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
		static public void CleanUp_Generated()
        {   		
			System.Console.WriteLine("All Tests Completed");
			System.Console.WriteLine();
        }
    
    
		/// <summary>
		/// Inserts a mock HocSinh entity into the database.
		/// </summary>
		private void Step_01_Insert_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.HocSinhProvider.Insert(tm, mock), "Insert failed");
										
				System.Console.WriteLine("DataRepository.HocSinhProvider.Insert(mock):");			
				System.Console.WriteLine(mock);			
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Selects all HocSinh objects of the database.
		/// </summary>
		private void Step_02_SelectAll_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Find
				int count = -1;
				
				mockCollection = DataRepository.HocSinhProvider.Find(tm, null, "", 0, 10, out count );
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
				
				System.Console.WriteLine("DataRepository.HocSinhProvider.Find():");			
				System.Console.WriteLine(mockCollection);
						
				
				// GetPaged
				count = -1;
				
				mockCollection = DataRepository.HocSinhProvider.GetPaged(tm, 0, 10, out count);
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue GetPaged Command.");
				System.Console.WriteLine("#get paged count: " + count.ToString());
			}
		}
		
		
		
		
		/// <summary>
		/// Deep load all HocSinh children.
		/// </summary>
		private void Step_03_DeepLoad_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				int count = -1;
				mock =  CreateMockInstance(tm);
				mockCollection = DataRepository.HocSinhProvider.GetPaged(tm, 0, 10, out count);
			
				DataRepository.HocSinhProvider.DeepLoading += new EntityProviderBaseCore<HocSinh, HocSinhKey>.DeepLoadingEventHandler(
						delegate(object sender, DeepSessionEventArgs e)
						{
							if (e.DeepSession.Count > 3)
								e.Cancel = true;
						}
					);

				if (mockCollection.Count > 0)
				{
					
					DataRepository.HocSinhProvider.DeepLoad(tm, mockCollection[0]);
					System.Console.WriteLine("HocSinh instance correctly deep loaded at 1 level.");
									
					mockCollection.Add(mock);
					DataRepository.HocSinhProvider.DeepSave(tm, mockCollection);
				}
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		/// <summary>
		/// Updates a mock HocSinh entity into the database.
		/// </summary>
		private void Step_04_Update_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				UpdateMockInstance(tm, mock);
				
				Assert.IsTrue(DataRepository.HocSinhProvider.Insert(tm, mock), "Insert failed");
				Assert.IsTrue(DataRepository.HocSinhProvider.Update(tm, mock), "Update failed.");			
				
				System.Console.WriteLine("DataRepository.HocSinhProvider.Update(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Delete the mock HocSinh entity into the database.
		/// </summary>
		private void Step_05_Delete_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  (HocSinh)CreateMockInstance(tm);
				DataRepository.HocSinhProvider.Insert(tm, mock);
			
				Assert.IsTrue(DataRepository.HocSinhProvider.Delete(tm, mock), "Delete failed.");
				System.Console.WriteLine("DataRepository.HocSinhProvider.Delete(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock HocSinh entity into a temporary file.
		/// </summary>
		private void Step_06_SerializeEntity_Generated()
		{	
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  CreateMockInstance(tm);
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_HocSinh.xml");
			
				EntityHelper.SerializeXml(mock, fileName);
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock not found");
					
				System.Console.WriteLine("mock correctly serialized to a temporary file.");			
			}
		}
		
		/// <summary>
		/// Deserialize the mock HocSinh entity from a temporary file.
		/// </summary>
		private void Step_07_DeserializeEntity_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_HocSinh.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			using (System.IO.StreamReader sr = System.IO.File.OpenText(fileName))
			{
				object item = EntityHelper.DeserializeEntityXml<HocSinh>(sr.ReadToEnd());
				sr.Close();
			}
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a HocSinh collection into a temporary file.
		/// </summary>
		private void Step_08_SerializeCollection_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_HocSinhCollection.xml");
				
				mock = CreateMockInstance(tm);
				TList<HocSinh> mockCollection = new TList<HocSinh>();
				mockCollection.Add(mock);
			
				EntityHelper.SerializeXml(mockCollection, fileName);
				
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock collection not found");
				System.Console.WriteLine("TList<HocSinh> correctly serialized to a temporary file.");					
			}
		}
		
		
		/// <summary>
		/// Deserialize a HocSinh collection from a temporary file.
		/// </summary>
		private void Step_09_DeserializeCollection_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_HocSinhCollection.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			XmlSerializer mySerializer = new XmlSerializer(typeof(TList<HocSinh>)); 
			using (System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open))
			{
				TList<HocSinh> mockCollection = (TList<HocSinh>) mySerializer.Deserialize(myFileStream);
				myFileStream.Close();
			}
			
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("TList<HocSinh> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		
		
		/// <summary>
		/// Check the foreign key dal methods.
		/// </summary>
		private void Step_10_FK_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				HocSinh entity = CreateMockInstance(tm);
				bool result = DataRepository.HocSinhProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test FK, Insert Failed");
				
				TList<HocSinh> t0 = DataRepository.HocSinhProvider.GetByMaLop(tm, entity.MaLop, 0, 10);
			}
		}
		
		
		/// <summary>
		/// Check the indexes dal methods.
		/// </summary>
		private void Step_11_IX_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				HocSinh entity = CreateMockInstance(tm);
				bool result = DataRepository.HocSinhProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test IX, Insert Failed");

			
				HocSinh t0 = DataRepository.HocSinhProvider.GetByMaHocSinh(tm, entity.MaHocSinh);
			}
		}
		
		/// <summary>
		/// Test methods exposed by the EntityHelper class.
		/// </summary>
		private void Step_20_TestEntityHelper_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				
				HocSinh entity = mock.Copy() as HocSinh;
				entity = (HocSinh)mock.Clone();
				Assert.IsTrue(entity.Equals(mock), "Clone is not working");
			}
		}
						
		#region Mock Instance
		///<summary>
		///  Returns a Typed HocSinh Entity with mock values.
		///</summary>
		static public HocSinh CreateMockInstance_Generated(TransactionManager tm)
		{		
			HocSinh mock = new HocSinh();
						
			mock.MaHocSinh = "V[PL57";
			mock.HoTenHocSinh = "HWOSBORNZDZFDZUAZXIQATBL";
			mock.GioiTinh = "HWOSBORNZDZFDZUAZXIQATBL";
			mock.NgaySinh = new DateTime(2009, 5, 5, 0, 6, 16, 187);
			mock.DiaChi = "HWOSBORNZDZFDZUAZXIQATBL";
			mock.Email = "";
			mock.XepLoai = "HWOSBORNZDZFDZUAZXIQATBL";
			mock.HanhKiem = "HWOSBORNZDZFDZUAZXIQATBL";
			mock.Password = "V[PL";
			
			int count0 = 0;
			TList<LopHoc> _collection0 = DataRepository.LopHocProvider.GetPaged(tm, 0, 10, out count0);
			//_collection0.Shuffle();
			if (_collection0.Count > 0)
			{
				mock.MaLop = _collection0[0].MaLop;
			}
		
			// create a temporary collection and add the item to it
			TList<HocSinh> tempMockCollection = new TList<HocSinh>();
			tempMockCollection.Add(mock);
			tempMockCollection.Remove(mock);
			
		
		   return (HocSinh)mock;
		}
		
		
		///<summary>
		///  Update the Typed HocSinh Entity with modified mock values.
		///</summary>
		static public void UpdateMockInstance_Generated(TransactionManager tm, HocSinh mock)
		{
			mock.MaHocSinh = "V[PL852";
			mock.HoTenHocSinh = "HWOSBORNZDZFDZUAZXIQATBL2";
			mock.GioiTinh = "HWOSBORNZDZFDZUAZXIQATBL2";
			mock.NgaySinh = new DateTime(2009, 5, 5, 0, 6, 16, 187);
			mock.DiaChi = "HWOSBORNZDZFDZUAZXIQATBL2";
			mock.Email = "2";
			mock.XepLoai = "HWOSBORNZDZFDZUAZXIQATBL2";
			mock.HanhKiem = "HWOSBORNZDZFDZUAZXIQATBL2";
			mock.Password = "V[PL2";
			
			int count0 = 0;
			TList<LopHoc> _collection0 = DataRepository.LopHocProvider.GetPaged(tm, 0, 10, out count0);
			//_collection0.Shuffle();
			if (_collection0.Count > 0)
			{
				mock.MaLop = _collection0[0].MaLop;
			}
		}
		#endregion
    }
}
