using System;
using System.ComponentModel;

namespace PTNK.Entities
{
	/// <summary>
	///		The data structure representation of the 'PhuTrach' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IPhuTrach 
	{
		/// <summary>			
		/// MaPhuTrach : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "PhuTrach"</remarks>
		System.String MaPhuTrach { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.String OriginalMaPhuTrach { get; set; }
			
		
		
		/// <summary>
		/// MaGiaoVien : 
		/// </summary>
		System.String  MaGiaoVien  { get; set; }
		
		/// <summary>
		/// MaMonHoc : 
		/// </summary>
		System.String  MaMonHoc  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


