
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file LopHoc.cs instead.
*/

#region using directives

using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

#endregion

namespace PTNK.Entities
{
	///<summary>
	/// An object representation of the 'LopHoc' table. [No description found the database]	
	///</summary>
	[Serializable, DataObject]
	[CLSCompliant(true)]
	public abstract partial class LopHocBase : EntityBase, PTNK.Entities.ILopHoc, IEntityId<LopHocKey>, System.IComparable, System.ICloneable, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private LopHocEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private LopHocEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private LopHocEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<LopHoc> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>	
		[field:NonSerialized]
		public event LopHocEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event LopHocEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="LopHocBase"/> instance.
		///</summary>
		public LopHocBase()
		{
			this.entityData = new LopHocEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="LopHocBase"/> instance.
		///</summary>
		///<param name="maLopHoc"></param>
		///<param name="tenLopHoc"></param>
		///<param name="maKhoi"></param>
		public LopHocBase(System.String maLopHoc, System.String tenLopHoc, System.String maKhoi)
		{
			this.entityData = new LopHocEntityData();
			this.backupData = null;

			this.MaLopHoc = maLopHoc;
			this.TenLopHoc = tenLopHoc;
			this.MaKhoi = maKhoi;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="LopHoc"/> instance.
		///</summary>
		///<param name="maLopHoc"></param>
		///<param name="tenLopHoc"></param>
		///<param name="maKhoi"></param>
		public static LopHoc CreateLopHoc(System.String maLopHoc, System.String tenLopHoc, System.String maKhoi)
		{
			LopHoc newLopHoc = new LopHoc();
			newLopHoc.MaLopHoc = maLopHoc;
			newLopHoc.TenLopHoc = tenLopHoc;
			newLopHoc.MaKhoi = maKhoi;
			return newLopHoc;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the MaLopHoc property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false, 4)]
		public virtual System.String MaLopHoc
		{
			get
			{
				return this.entityData.MaLopHoc; 
			}
			
			set
			{
				if (this.entityData.MaLopHoc == value)
					return;
					
				OnColumnChanging(LopHocColumn.MaLopHoc, this.entityData.MaLopHoc);
				this.entityData.MaLopHoc = value;
				this.EntityId.MaLopHoc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LopHocColumn.MaLopHoc, this.entityData.MaLopHoc);
				OnPropertyChanged("MaLopHoc");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the MaLopHoc property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the MaLopHoc property.</remarks>
		/// <value>This type is nvarchar</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.String OriginalMaLopHoc
		{
			get { return this.entityData.OriginalMaLopHoc; }
			set { this.entityData.OriginalMaLopHoc = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the TenLopHoc property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String TenLopHoc
		{
			get
			{
				return this.entityData.TenLopHoc; 
			}
			
			set
			{
				if (this.entityData.TenLopHoc == value)
					return;
					
				OnColumnChanging(LopHocColumn.TenLopHoc, this.entityData.TenLopHoc);
				this.entityData.TenLopHoc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LopHocColumn.TenLopHoc, this.entityData.TenLopHoc);
				OnPropertyChanged("TenLopHoc");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MaKhoi property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 3)]
		public virtual System.String MaKhoi
		{
			get
			{
				return this.entityData.MaKhoi; 
			}
			
			set
			{
				if (this.entityData.MaKhoi == value)
					return;
					
				OnColumnChanging(LopHocColumn.MaKhoi, this.entityData.MaKhoi);
				this.entityData.MaKhoi = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LopHocColumn.MaKhoi, this.entityData.MaKhoi);
				OnPropertyChanged("MaKhoi");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Khoi"/>.
		/// </summary>
		/// <value>The source Khoi for MaKhoi.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Khoi MaKhoiSource
      	{
            get { return entityData.MaKhoiSource; }
            set { entityData.MaKhoiSource = value; }
      	}
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of PhanCong objects
		///	which are related to this object through the relation PhanCong$LopHocPhanCong
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<PhanCong> PhanCongCollection
		{
			get { return entityData.PhanCongCollection; }
			set { entityData.PhanCongCollection = value; }	
		}
	
		/// <summary>
		///	Holds a collection of RangBuocLopHoc objects
		///	which are related to this object through the relation RangBuocLopHoc$LopHocRangBuocLopHoc
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<RangBuocLopHoc> RangBuocLopHocCollection
		{
			get { return entityData.RangBuocLopHocCollection; }
			set { entityData.RangBuocLopHocCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule(
				Validation.CommonRules.NotNull,
				new Validation.ValidationRuleArgs("MaLopHoc", "Ma Lop Hoc"));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("MaLopHoc", "Ma Lop Hoc", 4));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("TenLopHoc", "Ten Lop Hoc", 20));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("MaKhoi", "Ma Khoi", 3));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "LopHoc"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"MaLopHoc", "TenLopHoc", "MaKhoi"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as LopHocEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (LopHoc) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<LopHoc>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as LopHoc);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed LopHoc Entity 
		///</summary>
		public virtual LopHoc Copy()
		{
			//shallow copy entity
			LopHoc copy = new LopHoc();
			copy.SuppressEntityEvents = true;
			copy.MaLopHoc = this.MaLopHoc;
			copy.OriginalMaLopHoc = this.OriginalMaLopHoc;
			copy.TenLopHoc = this.TenLopHoc;
			copy.MaKhoi = this.MaKhoi;
			
			copy.MaKhoiSource = MakeCopyOf(this.MaKhoiSource) as Khoi;
		
			//deep copy nested objects
			copy.PhanCongCollection = (TList<PhanCong>) MakeCopyOf(this.PhanCongCollection); 
			copy.RangBuocLopHocCollection = (TList<RangBuocLopHoc>) MakeCopyOf(this.RangBuocLopHocCollection); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		///  Returns a Typed LopHoc Entity which is a deep copy of the current entity.
		///</summary>
		public virtual LopHoc DeepCopy()
		{
			return EntityHelper.Clone<LopHoc>(this as LopHoc);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as LopHocEntityData;
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as LopHocEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(LopHocColumn column)
		{
			switch(column)
			{
					case LopHocColumn.MaLopHoc:
					return entityData.MaLopHoc != _originalData.MaLopHoc;
					case LopHocColumn.TenLopHoc:
					return entityData.TenLopHoc != _originalData.TenLopHoc;
					case LopHocColumn.MaKhoi:
					return entityData.MaKhoi != _originalData.MaKhoi;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if [has data changed]; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.MaLopHoc != _originalData.MaLopHoc;
			result = result || entityData.TenLopHoc != _originalData.TenLopHoc;
			result = result || entityData.MaKhoi != _originalData.MaKhoi;
			return result;
}	
		
		#endregion

        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="LopHocBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			if (Object1 is LopHocBase)
				return Equals(this, (LopHocBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="LopHocBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.MaLopHoc.GetHashCode() ^ 
					((this.TenLopHoc == null) ? string.Empty : this.TenLopHoc.ToString()).GetHashCode() ^ 
					((this.MaKhoi == null) ? string.Empty : this.MaKhoi.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="LopHocBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(LopHocBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="LopHocBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="LopHocBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="LopHocBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(LopHocBase Object1, LopHocBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.MaLopHoc != Object2.MaLopHoc)
				equal = false;
			if ( Object1.TenLopHoc != null && Object2.TenLopHoc != null )
			{
				if (Object1.TenLopHoc != Object2.TenLopHoc)
					equal = false;
			}
			else if (Object1.TenLopHoc == null ^ Object2.TenLopHoc == null )
			{
				equal = false;
			}
			if ( Object1.MaKhoi != null && Object2.MaKhoi != null )
			{
				if (Object1.MaKhoi != Object2.MaKhoi)
					equal = false;
			}
			else if (Object1.MaKhoi == null ^ Object2.MaKhoi == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((LopHocBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static LopHocComparer GetComparer()
        {
            return new LopHocComparer();
        }
        */

        // Comparer delegates back to LopHoc
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(LopHoc rhs, LopHocColumn which)
        {
            switch (which)
            {
            	
            	
            	case LopHocColumn.MaLopHoc:
            		return this.MaLopHoc.CompareTo(rhs.MaLopHoc);
            		
            		                 
            	
            	
            	case LopHocColumn.TenLopHoc:
            		return this.TenLopHoc.CompareTo(rhs.TenLopHoc);
            		
            		                 
            	
            	
            	case LopHocColumn.MaKhoi:
            		return this.MaKhoi.CompareTo(rhs.MaKhoi);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<LopHocKey> Members
		
		// member variable for the EntityId property
		private LopHocKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual LopHocKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new LopHocKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("LopHoc")
					.Append("|").Append( this.MaLopHoc.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{4}{3}- MaLopHoc: {0}{3}- TenLopHoc: {1}{3}- MaKhoi: {2}{3}", 
				this.MaLopHoc,
				(this.TenLopHoc == null) ? string.Empty : this.TenLopHoc.ToString(),
				(this.MaKhoi == null) ? string.Empty : this.MaKhoi.ToString(),
				System.Environment.NewLine, 
				this.GetType());
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'LopHoc' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class LopHocEntityData : ICloneable
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
			/// <summary>			
			/// MaLopHoc : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "LopHoc"</remarks>
			public System.String MaLopHoc;
				
			/// <summary>
			/// keep a copy of the original so it can be used for editable primary keys.
			/// </summary>
			public System.String OriginalMaLopHoc;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// TenLopHoc : 
		/// </summary>
		public System.String		  TenLopHoc = null;
		
		/// <summary>
		/// MaKhoi : 
		/// </summary>
		public System.String		  MaKhoi = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private Khoi _maKhoiSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Khoi"/>.
		/// </summary>
		/// <value>The source Khoi for MaKhoi.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual Khoi MaKhoiSource
      	{
            get { return this._maKhoiSource; }
            set { this._maKhoiSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#region PhanCongCollection
		
		private TList<PhanCong> phanCongMaLopHoc;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation phanCongMaLopHoc
		/// </summary>	
		public TList<PhanCong> PhanCongCollection
		{
			get
			{
				if (phanCongMaLopHoc == null)
				{
				phanCongMaLopHoc = new TList<PhanCong>();
				}
	
				return phanCongMaLopHoc;
			}
			set { phanCongMaLopHoc = value; }
		}
		
		#endregion

		#region RangBuocLopHocCollection
		
		private TList<RangBuocLopHoc> rangBuocLopHocMaLopHoc;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation rangBuocLopHocMaLopHoc
		/// </summary>	
		public TList<RangBuocLopHoc> RangBuocLopHocCollection
		{
			get
			{
				if (rangBuocLopHocMaLopHoc == null)
				{
				rangBuocLopHocMaLopHoc = new TList<RangBuocLopHoc>();
				}
	
				return rangBuocLopHocMaLopHoc;
			}
			set { rangBuocLopHocMaLopHoc = value; }
		}
		
		#endregion

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			LopHocEntityData _tmp = new LopHocEntityData();
						
			_tmp.MaLopHoc = this.MaLopHoc;
			_tmp.OriginalMaLopHoc = this.OriginalMaLopHoc;
			
			_tmp.TenLopHoc = this.TenLopHoc;
			_tmp.MaKhoi = this.MaKhoi;
			
			#region Source Parent Composite Entities
			if (this.MaKhoiSource != null)
				_tmp.MaKhoiSource = MakeCopyOf(this.MaKhoiSource) as Khoi;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this.phanCongMaLopHoc != null)
				_tmp.PhanCongCollection = (TList<PhanCong>) MakeCopyOf(this.PhanCongCollection); 
			if (this.rangBuocLopHocMaLopHoc != null)
				_tmp.RangBuocLopHocCollection = (TList<RangBuocLopHoc>) MakeCopyOf(this.RangBuocLopHocCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct



		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LopHocColumn"/> which has raised the event.</param>
		public void OnColumnChanging(LopHocColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LopHocColumn"/> which has raised the event.</param>
		public void OnColumnChanged(LopHocColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LopHocColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanging(LopHocColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				LopHocEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new LopHocEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LopHocColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanged(LopHocColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				LopHocEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new LopHocEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region LopHocEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="LopHoc"/> object.
	/// </remarks>
	public class LopHocEventArgs : System.EventArgs
	{
		private LopHocColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the LopHocEventArgs class.
		///</summary>
		public LopHocEventArgs(LopHocColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the LopHocEventArgs class.
		///</summary>
		public LopHocEventArgs(LopHocColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The LopHocColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="LopHocColumn" />
		public LopHocColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all LopHoc related events.
	///</summary>
	public delegate void LopHocEventHandler(object sender, LopHocEventArgs e);
	
	#region LopHocComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class LopHocComparer : System.Collections.Generic.IComparer<LopHoc>
	{
		LopHocColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:LopHocComparer"/> class.
        /// </summary>
		public LopHocComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:LopHocComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public LopHocComparer(LopHocColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="LopHoc"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="LopHoc"/> to compare.</param>
        /// <param name="b">The second <c>LopHoc</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(LopHoc a, LopHoc b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(LopHoc entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(LopHoc a, LopHoc b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public LopHocColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region LopHocKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="LopHoc"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class LopHocKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the LopHocKey class.
		/// </summary>
		public LopHocKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the LopHocKey class.
		/// </summary>
		public LopHocKey(LopHocBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.MaLopHoc = entity.MaLopHoc;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the LopHocKey class.
		/// </summary>
		public LopHocKey(System.String maLopHoc)
		{
			#region Init Properties

			this.MaLopHoc = maLopHoc;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private LopHocBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public LopHocBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the MaLopHoc property
		private System.String _maLopHoc;
		
		/// <summary>
		/// Gets or sets the MaLopHoc property.
		/// </summary>
		public System.String MaLopHoc
		{
			get { return _maLopHoc; }
			set
			{
				if ( this.Entity != null )
					this.Entity.MaLopHoc = value;
				
				_maLopHoc = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				MaLopHoc = ( values["MaLopHoc"] != null ) ? (System.String) EntityUtil.ChangeType(values["MaLopHoc"], typeof(System.String)) : string.Empty;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("MaLopHoc", MaLopHoc);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("MaLopHoc: {0}{1}",
								MaLopHoc,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region LopHocColumn Enum
	
	/// <summary>
	/// Enumerate the LopHoc columns.
	/// </summary>
	[Serializable]
	public enum LopHocColumn : int
	{
		/// <summary>
		/// MaLopHoc : 
		/// </summary>
		[EnumTextValue("MaLopHoc")]
		[ColumnEnum("MaLopHoc", typeof(System.String), System.Data.DbType.String, true, false, false, 4)]
		MaLopHoc = 1,
		/// <summary>
		/// TenLopHoc : 
		/// </summary>
		[EnumTextValue("TenLopHoc")]
		[ColumnEnum("TenLopHoc", typeof(System.String), System.Data.DbType.String, false, false, true, 20)]
		TenLopHoc = 2,
		/// <summary>
		/// MaKhoi : 
		/// </summary>
		[EnumTextValue("MaKhoi")]
		[ColumnEnum("MaKhoi", typeof(System.String), System.Data.DbType.String, false, false, true, 3)]
		MaKhoi = 3
	}//End enum

	#endregion LopHocColumn Enum

} // end namespace
