
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file PhuTrach.cs instead.
*/

#region using directives

using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

#endregion

namespace PTNK.Entities
{
	///<summary>
	/// An object representation of the 'PhuTrach' table. [No description found the database]	
	///</summary>
	[Serializable, DataObject]
	[CLSCompliant(true)]
	public abstract partial class PhuTrachBase : EntityBase, PTNK.Entities.IPhuTrach, IEntityId<PhuTrachKey>, System.IComparable, System.ICloneable, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private PhuTrachEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private PhuTrachEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private PhuTrachEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<PhuTrach> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>	
		[field:NonSerialized]
		public event PhuTrachEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event PhuTrachEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="PhuTrachBase"/> instance.
		///</summary>
		public PhuTrachBase()
		{
			this.entityData = new PhuTrachEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="PhuTrachBase"/> instance.
		///</summary>
		///<param name="maPhuTrach"></param>
		///<param name="maGiaoVien"></param>
		///<param name="maMonHoc"></param>
		public PhuTrachBase(System.String maPhuTrach, System.String maGiaoVien, System.String maMonHoc)
		{
			this.entityData = new PhuTrachEntityData();
			this.backupData = null;

			this.MaPhuTrach = maPhuTrach;
			this.MaGiaoVien = maGiaoVien;
			this.MaMonHoc = maMonHoc;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="PhuTrach"/> instance.
		///</summary>
		///<param name="maPhuTrach"></param>
		///<param name="maGiaoVien"></param>
		///<param name="maMonHoc"></param>
		public static PhuTrach CreatePhuTrach(System.String maPhuTrach, System.String maGiaoVien, System.String maMonHoc)
		{
			PhuTrach newPhuTrach = new PhuTrach();
			newPhuTrach.MaPhuTrach = maPhuTrach;
			newPhuTrach.MaGiaoVien = maGiaoVien;
			newPhuTrach.MaMonHoc = maMonHoc;
			return newPhuTrach;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the MaPhuTrach property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false, 5)]
		public virtual System.String MaPhuTrach
		{
			get
			{
				return this.entityData.MaPhuTrach; 
			}
			
			set
			{
				if (this.entityData.MaPhuTrach == value)
					return;
					
				OnColumnChanging(PhuTrachColumn.MaPhuTrach, this.entityData.MaPhuTrach);
				this.entityData.MaPhuTrach = value;
				this.EntityId.MaPhuTrach = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PhuTrachColumn.MaPhuTrach, this.entityData.MaPhuTrach);
				OnPropertyChanged("MaPhuTrach");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the MaPhuTrach property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the MaPhuTrach property.</remarks>
		/// <value>This type is nvarchar</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.String OriginalMaPhuTrach
		{
			get { return this.entityData.OriginalMaPhuTrach; }
			set { this.entityData.OriginalMaPhuTrach = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the MaGiaoVien property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 5)]
		public virtual System.String MaGiaoVien
		{
			get
			{
				return this.entityData.MaGiaoVien; 
			}
			
			set
			{
				if (this.entityData.MaGiaoVien == value)
					return;
					
				OnColumnChanging(PhuTrachColumn.MaGiaoVien, this.entityData.MaGiaoVien);
				this.entityData.MaGiaoVien = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PhuTrachColumn.MaGiaoVien, this.entityData.MaGiaoVien);
				OnPropertyChanged("MaGiaoVien");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MaMonHoc property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 4)]
		public virtual System.String MaMonHoc
		{
			get
			{
				return this.entityData.MaMonHoc; 
			}
			
			set
			{
				if (this.entityData.MaMonHoc == value)
					return;
					
				OnColumnChanging(PhuTrachColumn.MaMonHoc, this.entityData.MaMonHoc);
				this.entityData.MaMonHoc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PhuTrachColumn.MaMonHoc, this.entityData.MaMonHoc);
				OnPropertyChanged("MaMonHoc");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="MonHoc"/>.
		/// </summary>
		/// <value>The source MonHoc for MaMonHoc.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual MonHoc MaMonHocSource
      	{
            get { return entityData.MaMonHocSource; }
            set { entityData.MaMonHocSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="GiaoVien"/>.
		/// </summary>
		/// <value>The source GiaoVien for MaGiaoVien.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual GiaoVien MaGiaoVienSource
      	{
            get { return entityData.MaGiaoVienSource; }
            set { entityData.MaGiaoVienSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule(
				Validation.CommonRules.NotNull,
				new Validation.ValidationRuleArgs("MaPhuTrach", "Ma Phu Trach"));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("MaPhuTrach", "Ma Phu Trach", 5));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("MaGiaoVien", "Ma Giao Vien", 5));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("MaMonHoc", "Ma Mon Hoc", 4));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "PhuTrach"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"MaPhuTrach", "MaGiaoVien", "MaMonHoc"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as PhuTrachEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (PhuTrach) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<PhuTrach>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as PhuTrach);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed PhuTrach Entity 
		///</summary>
		public virtual PhuTrach Copy()
		{
			//shallow copy entity
			PhuTrach copy = new PhuTrach();
			copy.SuppressEntityEvents = true;
			copy.MaPhuTrach = this.MaPhuTrach;
			copy.OriginalMaPhuTrach = this.OriginalMaPhuTrach;
			copy.MaGiaoVien = this.MaGiaoVien;
			copy.MaMonHoc = this.MaMonHoc;
			
			copy.MaMonHocSource = MakeCopyOf(this.MaMonHocSource) as MonHoc;
			copy.MaGiaoVienSource = MakeCopyOf(this.MaGiaoVienSource) as GiaoVien;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		///  Returns a Typed PhuTrach Entity which is a deep copy of the current entity.
		///</summary>
		public virtual PhuTrach DeepCopy()
		{
			return EntityHelper.Clone<PhuTrach>(this as PhuTrach);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as PhuTrachEntityData;
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as PhuTrachEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(PhuTrachColumn column)
		{
			switch(column)
			{
					case PhuTrachColumn.MaPhuTrach:
					return entityData.MaPhuTrach != _originalData.MaPhuTrach;
					case PhuTrachColumn.MaGiaoVien:
					return entityData.MaGiaoVien != _originalData.MaGiaoVien;
					case PhuTrachColumn.MaMonHoc:
					return entityData.MaMonHoc != _originalData.MaMonHoc;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if [has data changed]; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.MaPhuTrach != _originalData.MaPhuTrach;
			result = result || entityData.MaGiaoVien != _originalData.MaGiaoVien;
			result = result || entityData.MaMonHoc != _originalData.MaMonHoc;
			return result;
}	
		
		#endregion

        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="PhuTrachBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			if (Object1 is PhuTrachBase)
				return Equals(this, (PhuTrachBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="PhuTrachBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.MaPhuTrach.GetHashCode() ^ 
					((this.MaGiaoVien == null) ? string.Empty : this.MaGiaoVien.ToString()).GetHashCode() ^ 
					((this.MaMonHoc == null) ? string.Empty : this.MaMonHoc.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="PhuTrachBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(PhuTrachBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="PhuTrachBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="PhuTrachBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="PhuTrachBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(PhuTrachBase Object1, PhuTrachBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.MaPhuTrach != Object2.MaPhuTrach)
				equal = false;
			if ( Object1.MaGiaoVien != null && Object2.MaGiaoVien != null )
			{
				if (Object1.MaGiaoVien != Object2.MaGiaoVien)
					equal = false;
			}
			else if (Object1.MaGiaoVien == null ^ Object2.MaGiaoVien == null )
			{
				equal = false;
			}
			if ( Object1.MaMonHoc != null && Object2.MaMonHoc != null )
			{
				if (Object1.MaMonHoc != Object2.MaMonHoc)
					equal = false;
			}
			else if (Object1.MaMonHoc == null ^ Object2.MaMonHoc == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((PhuTrachBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static PhuTrachComparer GetComparer()
        {
            return new PhuTrachComparer();
        }
        */

        // Comparer delegates back to PhuTrach
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(PhuTrach rhs, PhuTrachColumn which)
        {
            switch (which)
            {
            	
            	
            	case PhuTrachColumn.MaPhuTrach:
            		return this.MaPhuTrach.CompareTo(rhs.MaPhuTrach);
            		
            		                 
            	
            	
            	case PhuTrachColumn.MaGiaoVien:
            		return this.MaGiaoVien.CompareTo(rhs.MaGiaoVien);
            		
            		                 
            	
            	
            	case PhuTrachColumn.MaMonHoc:
            		return this.MaMonHoc.CompareTo(rhs.MaMonHoc);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<PhuTrachKey> Members
		
		// member variable for the EntityId property
		private PhuTrachKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual PhuTrachKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new PhuTrachKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("PhuTrach")
					.Append("|").Append( this.MaPhuTrach.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{4}{3}- MaPhuTrach: {0}{3}- MaGiaoVien: {1}{3}- MaMonHoc: {2}{3}", 
				this.MaPhuTrach,
				(this.MaGiaoVien == null) ? string.Empty : this.MaGiaoVien.ToString(),
				(this.MaMonHoc == null) ? string.Empty : this.MaMonHoc.ToString(),
				System.Environment.NewLine, 
				this.GetType());
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'PhuTrach' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class PhuTrachEntityData : ICloneable
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
			/// <summary>			
			/// MaPhuTrach : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "PhuTrach"</remarks>
			public System.String MaPhuTrach;
				
			/// <summary>
			/// keep a copy of the original so it can be used for editable primary keys.
			/// </summary>
			public System.String OriginalMaPhuTrach;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// MaGiaoVien : 
		/// </summary>
		public System.String		  MaGiaoVien = null;
		
		/// <summary>
		/// MaMonHoc : 
		/// </summary>
		public System.String		  MaMonHoc = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private MonHoc _maMonHocSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="MonHoc"/>.
		/// </summary>
		/// <value>The source MonHoc for MaMonHoc.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual MonHoc MaMonHocSource
      	{
            get { return this._maMonHocSource; }
            set { this._maMonHocSource = value; }
      	}
		private GiaoVien _maGiaoVienSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="GiaoVien"/>.
		/// </summary>
		/// <value>The source GiaoVien for MaGiaoVien.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual GiaoVien MaGiaoVienSource
      	{
            get { return this._maGiaoVienSource; }
            set { this._maGiaoVienSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			PhuTrachEntityData _tmp = new PhuTrachEntityData();
						
			_tmp.MaPhuTrach = this.MaPhuTrach;
			_tmp.OriginalMaPhuTrach = this.OriginalMaPhuTrach;
			
			_tmp.MaGiaoVien = this.MaGiaoVien;
			_tmp.MaMonHoc = this.MaMonHoc;
			
			#region Source Parent Composite Entities
			if (this.MaMonHocSource != null)
				_tmp.MaMonHocSource = MakeCopyOf(this.MaMonHocSource) as MonHoc;
			if (this.MaGiaoVienSource != null)
				_tmp.MaGiaoVienSource = MakeCopyOf(this.MaGiaoVienSource) as GiaoVien;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct



		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PhuTrachColumn"/> which has raised the event.</param>
		public void OnColumnChanging(PhuTrachColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PhuTrachColumn"/> which has raised the event.</param>
		public void OnColumnChanged(PhuTrachColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PhuTrachColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanging(PhuTrachColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				PhuTrachEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new PhuTrachEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PhuTrachColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanged(PhuTrachColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				PhuTrachEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new PhuTrachEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region PhuTrachEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="PhuTrach"/> object.
	/// </remarks>
	public class PhuTrachEventArgs : System.EventArgs
	{
		private PhuTrachColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the PhuTrachEventArgs class.
		///</summary>
		public PhuTrachEventArgs(PhuTrachColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the PhuTrachEventArgs class.
		///</summary>
		public PhuTrachEventArgs(PhuTrachColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The PhuTrachColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="PhuTrachColumn" />
		public PhuTrachColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all PhuTrach related events.
	///</summary>
	public delegate void PhuTrachEventHandler(object sender, PhuTrachEventArgs e);
	
	#region PhuTrachComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class PhuTrachComparer : System.Collections.Generic.IComparer<PhuTrach>
	{
		PhuTrachColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:PhuTrachComparer"/> class.
        /// </summary>
		public PhuTrachComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:PhuTrachComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public PhuTrachComparer(PhuTrachColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="PhuTrach"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="PhuTrach"/> to compare.</param>
        /// <param name="b">The second <c>PhuTrach</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(PhuTrach a, PhuTrach b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(PhuTrach entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(PhuTrach a, PhuTrach b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public PhuTrachColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region PhuTrachKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="PhuTrach"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class PhuTrachKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the PhuTrachKey class.
		/// </summary>
		public PhuTrachKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the PhuTrachKey class.
		/// </summary>
		public PhuTrachKey(PhuTrachBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.MaPhuTrach = entity.MaPhuTrach;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the PhuTrachKey class.
		/// </summary>
		public PhuTrachKey(System.String maPhuTrach)
		{
			#region Init Properties

			this.MaPhuTrach = maPhuTrach;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private PhuTrachBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public PhuTrachBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the MaPhuTrach property
		private System.String _maPhuTrach;
		
		/// <summary>
		/// Gets or sets the MaPhuTrach property.
		/// </summary>
		public System.String MaPhuTrach
		{
			get { return _maPhuTrach; }
			set
			{
				if ( this.Entity != null )
					this.Entity.MaPhuTrach = value;
				
				_maPhuTrach = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				MaPhuTrach = ( values["MaPhuTrach"] != null ) ? (System.String) EntityUtil.ChangeType(values["MaPhuTrach"], typeof(System.String)) : string.Empty;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("MaPhuTrach", MaPhuTrach);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("MaPhuTrach: {0}{1}",
								MaPhuTrach,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region PhuTrachColumn Enum
	
	/// <summary>
	/// Enumerate the PhuTrach columns.
	/// </summary>
	[Serializable]
	public enum PhuTrachColumn : int
	{
		/// <summary>
		/// MaPhuTrach : 
		/// </summary>
		[EnumTextValue("MaPhuTrach")]
		[ColumnEnum("MaPhuTrach", typeof(System.String), System.Data.DbType.String, true, false, false, 5)]
		MaPhuTrach = 1,
		/// <summary>
		/// MaGiaoVien : 
		/// </summary>
		[EnumTextValue("MaGiaoVien")]
		[ColumnEnum("MaGiaoVien", typeof(System.String), System.Data.DbType.String, false, false, true, 5)]
		MaGiaoVien = 2,
		/// <summary>
		/// MaMonHoc : 
		/// </summary>
		[EnumTextValue("MaMonHoc")]
		[ColumnEnum("MaMonHoc", typeof(System.String), System.Data.DbType.String, false, false, true, 4)]
		MaMonHoc = 3
	}//End enum

	#endregion PhuTrachColumn Enum

} // end namespace
