
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file RangBuocLopHoc.cs instead.
*/

#region using directives

using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

#endregion

namespace PTNK.Entities
{
	///<summary>
	/// An object representation of the 'RangBuocLopHoc' table. [No description found the database]	
	///</summary>
	[Serializable, DataObject]
	[CLSCompliant(true)]
	public abstract partial class RangBuocLopHocBase : EntityBase, PTNK.Entities.IRangBuocLopHoc, IEntityId<RangBuocLopHocKey>, System.IComparable, System.ICloneable, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private RangBuocLopHocEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private RangBuocLopHocEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private RangBuocLopHocEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<RangBuocLopHoc> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>	
		[field:NonSerialized]
		public event RangBuocLopHocEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event RangBuocLopHocEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="RangBuocLopHocBase"/> instance.
		///</summary>
		public RangBuocLopHocBase()
		{
			this.entityData = new RangBuocLopHocEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="RangBuocLopHocBase"/> instance.
		///</summary>
		///<param name="maRangBuocLopHoc"></param>
		///<param name="maLopHoc"></param>
		///<param name="thu"></param>
		///<param name="tietHoc"></param>
		///<param name="trangThai"></param>
		public RangBuocLopHocBase(System.String maRangBuocLopHoc, System.String maLopHoc, 
			System.Byte? thu, System.Byte? tietHoc, System.Byte? trangThai)
		{
			this.entityData = new RangBuocLopHocEntityData();
			this.backupData = null;

			this.MaRangBuocLopHoc = maRangBuocLopHoc;
			this.MaLopHoc = maLopHoc;
			this.Thu = thu;
			this.TietHoc = tietHoc;
			this.TrangThai = trangThai;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="RangBuocLopHoc"/> instance.
		///</summary>
		///<param name="maRangBuocLopHoc"></param>
		///<param name="maLopHoc"></param>
		///<param name="thu"></param>
		///<param name="tietHoc"></param>
		///<param name="trangThai"></param>
		public static RangBuocLopHoc CreateRangBuocLopHoc(System.String maRangBuocLopHoc, System.String maLopHoc, 
			System.Byte? thu, System.Byte? tietHoc, System.Byte? trangThai)
		{
			RangBuocLopHoc newRangBuocLopHoc = new RangBuocLopHoc();
			newRangBuocLopHoc.MaRangBuocLopHoc = maRangBuocLopHoc;
			newRangBuocLopHoc.MaLopHoc = maLopHoc;
			newRangBuocLopHoc.Thu = thu;
			newRangBuocLopHoc.TietHoc = tietHoc;
			newRangBuocLopHoc.TrangThai = trangThai;
			return newRangBuocLopHoc;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the MaRangBuocLopHoc property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false, 9)]
		public virtual System.String MaRangBuocLopHoc
		{
			get
			{
				return this.entityData.MaRangBuocLopHoc; 
			}
			
			set
			{
				if (this.entityData.MaRangBuocLopHoc == value)
					return;
					
				OnColumnChanging(RangBuocLopHocColumn.MaRangBuocLopHoc, this.entityData.MaRangBuocLopHoc);
				this.entityData.MaRangBuocLopHoc = value;
				this.EntityId.MaRangBuocLopHoc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(RangBuocLopHocColumn.MaRangBuocLopHoc, this.entityData.MaRangBuocLopHoc);
				OnPropertyChanged("MaRangBuocLopHoc");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the MaRangBuocLopHoc property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the MaRangBuocLopHoc property.</remarks>
		/// <value>This type is nvarchar</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.String OriginalMaRangBuocLopHoc
		{
			get { return this.entityData.OriginalMaRangBuocLopHoc; }
			set { this.entityData.OriginalMaRangBuocLopHoc = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the MaLopHoc property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 4)]
		public virtual System.String MaLopHoc
		{
			get
			{
				return this.entityData.MaLopHoc; 
			}
			
			set
			{
				if (this.entityData.MaLopHoc == value)
					return;
					
				OnColumnChanging(RangBuocLopHocColumn.MaLopHoc, this.entityData.MaLopHoc);
				this.entityData.MaLopHoc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(RangBuocLopHocColumn.MaLopHoc, this.entityData.MaLopHoc);
				OnPropertyChanged("MaLopHoc");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Thu property. 
		///		
		/// </summary>
		/// <value>This type is tinyint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (byte)0. It is up to the developer
		/// to check the value of IsThuNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Byte? Thu
		{
			get
			{
				return this.entityData.Thu; 
			}
			
			set
			{
				if (this.entityData.Thu == value)
					return;
					
				OnColumnChanging(RangBuocLopHocColumn.Thu, this.entityData.Thu);
				this.entityData.Thu = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(RangBuocLopHocColumn.Thu, this.entityData.Thu);
				OnPropertyChanged("Thu");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TietHoc property. 
		///		
		/// </summary>
		/// <value>This type is tinyint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (byte)0. It is up to the developer
		/// to check the value of IsTietHocNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Byte? TietHoc
		{
			get
			{
				return this.entityData.TietHoc; 
			}
			
			set
			{
				if (this.entityData.TietHoc == value)
					return;
					
				OnColumnChanging(RangBuocLopHocColumn.TietHoc, this.entityData.TietHoc);
				this.entityData.TietHoc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(RangBuocLopHocColumn.TietHoc, this.entityData.TietHoc);
				OnPropertyChanged("TietHoc");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TrangThai property. 
		///		
		/// </summary>
		/// <value>This type is tinyint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (byte)0. It is up to the developer
		/// to check the value of IsTrangThaiNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Byte? TrangThai
		{
			get
			{
				return this.entityData.TrangThai; 
			}
			
			set
			{
				if (this.entityData.TrangThai == value)
					return;
					
				OnColumnChanging(RangBuocLopHocColumn.TrangThai, this.entityData.TrangThai);
				this.entityData.TrangThai = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(RangBuocLopHocColumn.TrangThai, this.entityData.TrangThai);
				OnPropertyChanged("TrangThai");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="LopHoc"/>.
		/// </summary>
		/// <value>The source LopHoc for MaLopHoc.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual LopHoc MaLopHocSource
      	{
            get { return entityData.MaLopHocSource; }
            set { entityData.MaLopHocSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule(
				Validation.CommonRules.NotNull,
				new Validation.ValidationRuleArgs("MaRangBuocLopHoc", "Ma Rang Buoc Lop Hoc"));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("MaRangBuocLopHoc", "Ma Rang Buoc Lop Hoc", 9));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("MaLopHoc", "Ma Lop Hoc", 4));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "RangBuocLopHoc"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"MaRangBuocLopHoc", "MaLopHoc", "Thu", "TietHoc", "TrangThai"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as RangBuocLopHocEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (RangBuocLopHoc) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<RangBuocLopHoc>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as RangBuocLopHoc);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed RangBuocLopHoc Entity 
		///</summary>
		public virtual RangBuocLopHoc Copy()
		{
			//shallow copy entity
			RangBuocLopHoc copy = new RangBuocLopHoc();
			copy.SuppressEntityEvents = true;
			copy.MaRangBuocLopHoc = this.MaRangBuocLopHoc;
			copy.OriginalMaRangBuocLopHoc = this.OriginalMaRangBuocLopHoc;
			copy.MaLopHoc = this.MaLopHoc;
			copy.Thu = this.Thu;
			copy.TietHoc = this.TietHoc;
			copy.TrangThai = this.TrangThai;
			
			copy.MaLopHocSource = MakeCopyOf(this.MaLopHocSource) as LopHoc;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		///  Returns a Typed RangBuocLopHoc Entity which is a deep copy of the current entity.
		///</summary>
		public virtual RangBuocLopHoc DeepCopy()
		{
			return EntityHelper.Clone<RangBuocLopHoc>(this as RangBuocLopHoc);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as RangBuocLopHocEntityData;
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as RangBuocLopHocEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(RangBuocLopHocColumn column)
		{
			switch(column)
			{
					case RangBuocLopHocColumn.MaRangBuocLopHoc:
					return entityData.MaRangBuocLopHoc != _originalData.MaRangBuocLopHoc;
					case RangBuocLopHocColumn.MaLopHoc:
					return entityData.MaLopHoc != _originalData.MaLopHoc;
					case RangBuocLopHocColumn.Thu:
					return entityData.Thu != _originalData.Thu;
					case RangBuocLopHocColumn.TietHoc:
					return entityData.TietHoc != _originalData.TietHoc;
					case RangBuocLopHocColumn.TrangThai:
					return entityData.TrangThai != _originalData.TrangThai;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if [has data changed]; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.MaRangBuocLopHoc != _originalData.MaRangBuocLopHoc;
			result = result || entityData.MaLopHoc != _originalData.MaLopHoc;
			result = result || entityData.Thu != _originalData.Thu;
			result = result || entityData.TietHoc != _originalData.TietHoc;
			result = result || entityData.TrangThai != _originalData.TrangThai;
			return result;
}	
		
		#endregion

        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="RangBuocLopHocBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			if (Object1 is RangBuocLopHocBase)
				return Equals(this, (RangBuocLopHocBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="RangBuocLopHocBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.MaRangBuocLopHoc.GetHashCode() ^ 
					((this.MaLopHoc == null) ? string.Empty : this.MaLopHoc.ToString()).GetHashCode() ^ 
					((this.Thu == null) ? string.Empty : this.Thu.ToString()).GetHashCode() ^ 
					((this.TietHoc == null) ? string.Empty : this.TietHoc.ToString()).GetHashCode() ^ 
					((this.TrangThai == null) ? string.Empty : this.TrangThai.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="RangBuocLopHocBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(RangBuocLopHocBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="RangBuocLopHocBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="RangBuocLopHocBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="RangBuocLopHocBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(RangBuocLopHocBase Object1, RangBuocLopHocBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.MaRangBuocLopHoc != Object2.MaRangBuocLopHoc)
				equal = false;
			if ( Object1.MaLopHoc != null && Object2.MaLopHoc != null )
			{
				if (Object1.MaLopHoc != Object2.MaLopHoc)
					equal = false;
			}
			else if (Object1.MaLopHoc == null ^ Object2.MaLopHoc == null )
			{
				equal = false;
			}
			if ( Object1.Thu != null && Object2.Thu != null )
			{
				if (Object1.Thu != Object2.Thu)
					equal = false;
			}
			else if (Object1.Thu == null ^ Object2.Thu == null )
			{
				equal = false;
			}
			if ( Object1.TietHoc != null && Object2.TietHoc != null )
			{
				if (Object1.TietHoc != Object2.TietHoc)
					equal = false;
			}
			else if (Object1.TietHoc == null ^ Object2.TietHoc == null )
			{
				equal = false;
			}
			if ( Object1.TrangThai != null && Object2.TrangThai != null )
			{
				if (Object1.TrangThai != Object2.TrangThai)
					equal = false;
			}
			else if (Object1.TrangThai == null ^ Object2.TrangThai == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((RangBuocLopHocBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static RangBuocLopHocComparer GetComparer()
        {
            return new RangBuocLopHocComparer();
        }
        */

        // Comparer delegates back to RangBuocLopHoc
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(RangBuocLopHoc rhs, RangBuocLopHocColumn which)
        {
            switch (which)
            {
            	
            	
            	case RangBuocLopHocColumn.MaRangBuocLopHoc:
            		return this.MaRangBuocLopHoc.CompareTo(rhs.MaRangBuocLopHoc);
            		
            		                 
            	
            	
            	case RangBuocLopHocColumn.MaLopHoc:
            		return this.MaLopHoc.CompareTo(rhs.MaLopHoc);
            		
            		                 
            	
            	
            	case RangBuocLopHocColumn.Thu:
            		return this.Thu.Value.CompareTo(rhs.Thu.Value);
            		
            		                 
            	
            	
            	case RangBuocLopHocColumn.TietHoc:
            		return this.TietHoc.Value.CompareTo(rhs.TietHoc.Value);
            		
            		                 
            	
            	
            	case RangBuocLopHocColumn.TrangThai:
            		return this.TrangThai.Value.CompareTo(rhs.TrangThai.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<RangBuocLopHocKey> Members
		
		// member variable for the EntityId property
		private RangBuocLopHocKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual RangBuocLopHocKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new RangBuocLopHocKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("RangBuocLopHoc")
					.Append("|").Append( this.MaRangBuocLopHoc.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{6}{5}- MaRangBuocLopHoc: {0}{5}- MaLopHoc: {1}{5}- Thu: {2}{5}- TietHoc: {3}{5}- TrangThai: {4}{5}", 
				this.MaRangBuocLopHoc,
				(this.MaLopHoc == null) ? string.Empty : this.MaLopHoc.ToString(),
				(this.Thu == null) ? string.Empty : this.Thu.ToString(),
				(this.TietHoc == null) ? string.Empty : this.TietHoc.ToString(),
				(this.TrangThai == null) ? string.Empty : this.TrangThai.ToString(),
				System.Environment.NewLine, 
				this.GetType());
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'RangBuocLopHoc' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class RangBuocLopHocEntityData : ICloneable
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
			/// <summary>			
			/// MaRangBuocLopHoc : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "RangBuocLopHoc"</remarks>
			public System.String MaRangBuocLopHoc;
				
			/// <summary>
			/// keep a copy of the original so it can be used for editable primary keys.
			/// </summary>
			public System.String OriginalMaRangBuocLopHoc;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// MaLopHoc : 
		/// </summary>
		public System.String		  MaLopHoc = null;
		
		/// <summary>
		/// Thu : 
		/// </summary>
		public System.Byte?		  Thu = null;
		
		/// <summary>
		/// TietHoc : 
		/// </summary>
		public System.Byte?		  TietHoc = null;
		
		/// <summary>
		/// TrangThai : 
		/// </summary>
		public System.Byte?		  TrangThai = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private LopHoc _maLopHocSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="LopHoc"/>.
		/// </summary>
		/// <value>The source LopHoc for MaLopHoc.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual LopHoc MaLopHocSource
      	{
            get { return this._maLopHocSource; }
            set { this._maLopHocSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			RangBuocLopHocEntityData _tmp = new RangBuocLopHocEntityData();
						
			_tmp.MaRangBuocLopHoc = this.MaRangBuocLopHoc;
			_tmp.OriginalMaRangBuocLopHoc = this.OriginalMaRangBuocLopHoc;
			
			_tmp.MaLopHoc = this.MaLopHoc;
			_tmp.Thu = this.Thu;
			_tmp.TietHoc = this.TietHoc;
			_tmp.TrangThai = this.TrangThai;
			
			#region Source Parent Composite Entities
			if (this.MaLopHocSource != null)
				_tmp.MaLopHocSource = MakeCopyOf(this.MaLopHocSource) as LopHoc;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct



		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="RangBuocLopHocColumn"/> which has raised the event.</param>
		public void OnColumnChanging(RangBuocLopHocColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="RangBuocLopHocColumn"/> which has raised the event.</param>
		public void OnColumnChanged(RangBuocLopHocColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="RangBuocLopHocColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanging(RangBuocLopHocColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				RangBuocLopHocEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new RangBuocLopHocEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="RangBuocLopHocColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanged(RangBuocLopHocColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				RangBuocLopHocEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new RangBuocLopHocEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region RangBuocLopHocEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="RangBuocLopHoc"/> object.
	/// </remarks>
	public class RangBuocLopHocEventArgs : System.EventArgs
	{
		private RangBuocLopHocColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the RangBuocLopHocEventArgs class.
		///</summary>
		public RangBuocLopHocEventArgs(RangBuocLopHocColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the RangBuocLopHocEventArgs class.
		///</summary>
		public RangBuocLopHocEventArgs(RangBuocLopHocColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The RangBuocLopHocColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="RangBuocLopHocColumn" />
		public RangBuocLopHocColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all RangBuocLopHoc related events.
	///</summary>
	public delegate void RangBuocLopHocEventHandler(object sender, RangBuocLopHocEventArgs e);
	
	#region RangBuocLopHocComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class RangBuocLopHocComparer : System.Collections.Generic.IComparer<RangBuocLopHoc>
	{
		RangBuocLopHocColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:RangBuocLopHocComparer"/> class.
        /// </summary>
		public RangBuocLopHocComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:RangBuocLopHocComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public RangBuocLopHocComparer(RangBuocLopHocColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="RangBuocLopHoc"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="RangBuocLopHoc"/> to compare.</param>
        /// <param name="b">The second <c>RangBuocLopHoc</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(RangBuocLopHoc a, RangBuocLopHoc b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(RangBuocLopHoc entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(RangBuocLopHoc a, RangBuocLopHoc b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public RangBuocLopHocColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region RangBuocLopHocKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="RangBuocLopHoc"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class RangBuocLopHocKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the RangBuocLopHocKey class.
		/// </summary>
		public RangBuocLopHocKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the RangBuocLopHocKey class.
		/// </summary>
		public RangBuocLopHocKey(RangBuocLopHocBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.MaRangBuocLopHoc = entity.MaRangBuocLopHoc;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the RangBuocLopHocKey class.
		/// </summary>
		public RangBuocLopHocKey(System.String maRangBuocLopHoc)
		{
			#region Init Properties

			this.MaRangBuocLopHoc = maRangBuocLopHoc;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private RangBuocLopHocBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public RangBuocLopHocBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the MaRangBuocLopHoc property
		private System.String _maRangBuocLopHoc;
		
		/// <summary>
		/// Gets or sets the MaRangBuocLopHoc property.
		/// </summary>
		public System.String MaRangBuocLopHoc
		{
			get { return _maRangBuocLopHoc; }
			set
			{
				if ( this.Entity != null )
					this.Entity.MaRangBuocLopHoc = value;
				
				_maRangBuocLopHoc = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				MaRangBuocLopHoc = ( values["MaRangBuocLopHoc"] != null ) ? (System.String) EntityUtil.ChangeType(values["MaRangBuocLopHoc"], typeof(System.String)) : string.Empty;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("MaRangBuocLopHoc", MaRangBuocLopHoc);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("MaRangBuocLopHoc: {0}{1}",
								MaRangBuocLopHoc,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region RangBuocLopHocColumn Enum
	
	/// <summary>
	/// Enumerate the RangBuocLopHoc columns.
	/// </summary>
	[Serializable]
	public enum RangBuocLopHocColumn : int
	{
		/// <summary>
		/// MaRangBuocLopHoc : 
		/// </summary>
		[EnumTextValue("MaRangBuocLopHoc")]
		[ColumnEnum("MaRangBuocLopHoc", typeof(System.String), System.Data.DbType.String, true, false, false, 9)]
		MaRangBuocLopHoc = 1,
		/// <summary>
		/// MaLopHoc : 
		/// </summary>
		[EnumTextValue("MaLopHoc")]
		[ColumnEnum("MaLopHoc", typeof(System.String), System.Data.DbType.String, false, false, true, 4)]
		MaLopHoc = 2,
		/// <summary>
		/// Thu : 
		/// </summary>
		[EnumTextValue("Thu")]
		[ColumnEnum("Thu", typeof(System.Byte), System.Data.DbType.Byte, false, false, true)]
		Thu = 3,
		/// <summary>
		/// TietHoc : 
		/// </summary>
		[EnumTextValue("TietHoc")]
		[ColumnEnum("TietHoc", typeof(System.Byte), System.Data.DbType.Byte, false, false, true)]
		TietHoc = 4,
		/// <summary>
		/// TrangThai : 
		/// </summary>
		[EnumTextValue("TrangThai")]
		[ColumnEnum("TrangThai", typeof(System.Byte), System.Data.DbType.Byte, false, false, true)]
		TrangThai = 5
	}//End enum

	#endregion RangBuocLopHocColumn Enum

} // end namespace
